steps:
  - id: 'Initialize Terraform'
    name: "hashicorp/terraform:1.0.0"
    entrypoint: 'sh'
    args:
      - '-c'
      - |
        echo "*******************"
        echo "Terraform Init"
        echo "*******************"
        terraform init -backend-config="bucket=test-bucket-91" -backend-config="prefix=test/state" || exit 1

  - id: 'Validate Terraform'
    name: "hashicorp/terraform:1.0.0"
    entrypoint: 'sh'
    args:
      - '-c'
      - |
        echo "*******************"
        echo "Terraform Validate"
        echo "*******************"
        terraform validate

  - id: 'Terraform Plan'
    name: "hashicorp/terraform:1.0.0"
    entrypoint: 'sh'
    args:
      - '-c'
      - |
        echo "*******************"
        echo "Terraform Plan"
        echo "*******************"
        terraform plan

  - id: 'Terraform Apply'
    name: "hashicorp/terraform:1.0.0"
    entrypoint: 'sh'
    args:
      - '-c'
      - |
        echo "*******************"
        echo "Terraform Apply"
        echo "*******************"
        terraform apply --auto-approve

  - id: 'Worker pool'
    name: 'bash'
    entrypoint: 'sh'
    args:
      - '-c'
      - |
        echo "I am running in a private pool!"
options:
  logging: CLOUD_LOGGING_ONLY
